"""empty message

Revision ID: b56027d05c3a
Revises: ffdc0a98111c
Create Date: 2024-04-06 12:57:23.891709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56027d05c3a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageable_type', sa.String(length=40), nullable=False),
    sa.Column('imageable_id', sa.Integer(), nullable=False),
    sa.Column('preview', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=40), nullable=False),
    sa.Column('series', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('edition', sa.String(length=40), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=False),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], )
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_item_id', sa.Integer(), nullable=False),
    sa.Column('seller_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seller_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('list_items')
    op.drop_table('lists')
    op.drop_table('items')
    op.drop_table('images')
    # ### end Alembic commands ###
